Bootstrap Components to Material-UI (login, Signup)
DhananjayThomble/URL-Shortener-App pull request #184
Opened 2024-09-24 05:18 UTC by chiragmalik2612

## Before ( Bootstrap components) 

![Screenshot (2248)](https://github.com/user-attachments/assets/f2f1102e-b32b-4bb0-9b8e-d36c425ba871)
![Screenshot (2250)](https://github.com/user-attachments/assets/a2d1f883-d99e-4a2f-9fdd-165f4358129f)

##After ( Material UI components)

![Screenshot (2249)](https://github.com/user-attachments/assets/d2d7108e-49e5-4971-9d94-f7a5710643dc)

![Screenshot (2252)](https://github.com/user-attachments/assets/0720d48a-b1c2-46a9-83a0-5b8ee326cf28)

2024-09-24 08:28 UTC, DhananjayThomble requested changes

2024-09-24 08:28 UTC, DhananjayThomble commented on frontend/src/components/Signup.jsx
> +                  onChange={(e) => setEmail(e.target.value)}
can you please test the signup component? I think you've called the wrong function to set the name input field.

2024-09-24 15:35 UTC, chiragmalik2612 commented on frontend/src/components/Signup.jsx
> +                  onChange={(e) => setEmail(e.target.value)}
> can you please test the signup component? I think you've called the wrong function to set the name input field.

typo fixed , I think everything is fine now

2024-09-25 03:36 UTC, chiragmalik2612 commented
@DhananjayThomble , will this be count in hacktoberfest?

2024-09-25 05:44 UTC, DhananjayThomble commented
> @DhananjayThomble , will this be count in hacktoberfest?

Not now. Let the event begin first.

2024-09-25 05:46 UTC, merged